// focus/styles.js — FocusScreen 전용 스타일 (FocusScreen.js에서 분리, 코드 변경 없음)
import { StyleSheet, Dimensions } from 'react-native';

const SW = Dimensions.get('window').width;
const isTablet = SW >= 600;
export const GAP = 8;
export const CONTENT_MAX_W_STATIC = isTablet ? 680 : SW;

export function createStyles(fs) { return StyleSheet.create({
  container: { flex: 1 }, scrollCol: { paddingHorizontal: 16, paddingTop: 8, paddingBottom: 100 },
  scroll: { paddingHorizontal: 16, paddingTop: 8, paddingBottom: 100 },
  tabletBlock: { width: CONTENT_MAX_W_STATIC },
  headerCard: { borderRadius: 14, paddingHorizontal: 12, paddingVertical: 10, marginBottom: 8, overflow: 'hidden' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  headerLeft: { flexDirection: 'row', alignItems: 'center', flex: 1, marginRight: 8 },
  title: { fontSize: Math.round(15 * fs), fontWeight: '800' }, headerSub: { fontSize: Math.round(11 * fs), marginTop: 1 },
  darkBtn: { width: 32, height: 32, borderRadius: 8, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  ddayGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginBottom: 6 },
  ddayCell: { width: (CONTENT_MAX_W_STATIC - 32 - 12) / 4, paddingVertical: 4, borderRadius: 6, borderWidth: 1, alignItems: 'center' },
  ddayCellLabel: { fontSize: Math.round(11 * fs), fontWeight: '700' }, ddayCellVal: { fontSize: Math.round(11 * fs), fontWeight: '900', marginTop: 1 },
  planCard: { borderRadius: 14, borderWidth: 1, marginBottom: 8, overflow: 'hidden' },
  planCardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 12, paddingVertical: 10 },
  planCardTitle: { fontSize: Math.round(14 * fs), fontWeight: '800' },
  planEditBtn: { fontSize: Math.round(14 * fs), fontWeight: '700' },
  planFixedRow: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 4 },
  planFixedIcon: { fontSize: Math.round(14 * fs) },
  planFixedLabel: { flex: 1, fontSize: Math.round(13 * fs), fontWeight: '500' },
  planFixedTime: { fontSize: Math.round(12 * fs), fontWeight: '500' },
  planDivider: { height: 1, marginHorizontal: 12, marginVertical: 4 },
  planRow: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 6 },
  planRowIcon: { fontSize: Math.round(16 * fs) },
  planLabel: { fontSize: Math.round(14 * fs), fontWeight: '600' },
  planMiniTrack: { height: 3, borderRadius: 2, marginTop: 3, overflow: 'hidden' },
  planMiniFill: { height: 3, borderRadius: 2 },
  planTime: { fontSize: Math.round(12 * fs), minWidth: 54, textAlign: 'right', fontWeight: '600' },
  planAction: { width: 32, alignItems: 'center' },
  planPlayBtn: { width: 26, height: 26, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  planPlayBtnT: { color: 'white', fontSize: Math.round(12 * fs), fontWeight: '800' },
  planProgress: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 12, paddingVertical: 8, paddingTop: 4 },
  planProgTrack: { flex: 1, height: 5, borderRadius: 3, overflow: 'hidden' },
  planProgFill: { height: 5, borderRadius: 3 },
  planProgLabel: { fontSize: Math.round(12 * fs), fontWeight: '700', minWidth: 52, textAlign: 'right' },
  roomPill: { flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 10, borderWidth: 1, paddingVertical: 8, paddingHorizontal: 12, marginBottom: 8 },
  roomPillText: { flex: 1, fontSize: Math.round(12.5 * fs), fontWeight: '800' },
  progCard: { borderRadius: 12, padding: 10, borderWidth: 1, marginBottom: 8 },
  progRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  progLabel: { fontSize: Math.round(12 * fs), fontWeight: '600' }, progVal: { fontSize: Math.round(15 * fs), fontWeight: '900' },
  progTrack: { height: 5, borderRadius: 3, overflow: 'hidden' }, progFill: { height: '100%', borderRadius: 3 },
  quickSec: { borderRadius: 14, padding: 10, borderWidth: 1, marginBottom: 8 },
  quickHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  quickTitle: { fontSize: Math.round(14 * fs), fontWeight: '800' }, quickEdit: { fontSize: Math.round(12 * fs), fontWeight: '700' },
  favTabBtn: { paddingHorizontal: 10, paddingTop: 5, paddingBottom: 7, borderRadius: 8, borderWidth: 1 },
  favTabBtnT: { fontSize: Math.round(12 * fs), fontWeight: '700', lineHeight: 16 },
  quickBody: {},
  favGrid: { flexDirection: 'row', gap: 6, marginBottom: 6 },
  favCell: { flex: 1, borderRadius: 10, borderWidth: 1, paddingVertical: 10, minHeight: 62, alignItems: 'center', justifyContent: 'center' },
  favCellIcon: { fontSize: Math.round(18 * fs), marginBottom: 2 }, favCellLabel: { fontSize: Math.round(11 * fs), fontWeight: '700' },
  favEmpty: { fontSize: Math.round(12 * fs), padding: 10 },
  customBtn: { borderRadius: 10, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, marginTop: 2 },
  customBtnIcon: { fontSize: Math.round(14 * fs) }, customBtnLabel: { color: 'white', fontSize: Math.round(13 * fs), fontWeight: '800' },
  queueCard: { borderRadius: 14, padding: 10, borderWidth: 1.5, marginBottom: 8 },
  queueTitle: { fontSize: Math.round(14 * fs), fontWeight: '800' }, queueCancel: { fontSize: Math.round(13 * fs), fontWeight: '700' },
  timerFixedArea: { borderBottomWidth: 1 },
  timerSec: { marginBottom: 8 }, secTitle: { fontSize: Math.round(12 * fs), fontWeight: '700', marginBottom: 5 },
  timerGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: GAP },
  tc: { borderRadius: 12, padding: 10 },
  tcTop: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 2 },
  tcIcon: { fontSize: Math.round(14 * fs) }, tcLabel: { flex: 1, fontSize: Math.round(12 * fs), fontWeight: '700' }, tcClose: { fontSize: Math.round(14 * fs), fontWeight: '600' },
  tcPhase: { fontSize: Math.round(11 * fs), fontWeight: '700', marginBottom: 1 },
  tcTime: { fontWeight: '900', fontVariant: ['tabular-nums'], textAlign: 'center', marginVertical: 3 },
  tcElapsed: { fontSize: Math.round(11 * fs), textAlign: 'center', marginBottom: 2 },
  tcTrack: { height: 3, borderRadius: 2, overflow: 'hidden', marginBottom: 5 }, tcFill: { height: '100%', borderRadius: 2 },
  tcCtrls: { flexDirection: 'row', gap: 4 },
  tcBtn: { flex: 1, paddingVertical: 6, borderRadius: 7, alignItems: 'center' }, tcBtnT: { color: 'white', fontSize: Math.round(13 * fs), fontWeight: '800' },
  resArea: { alignItems: 'center', paddingVertical: 4 }, resEmoji: { fontSize: Math.round(18 * fs), marginBottom: 2 },
  resTier: { paddingHorizontal: 10, paddingVertical: 2, borderRadius: 6, marginBottom: 2 },
  resTierT: { fontSize: Math.round(15 * fs), fontWeight: '900' }, resDensity: { fontSize: Math.round(12 * fs), fontWeight: '700' }, resTime: { fontSize: Math.round(11 * fs), marginTop: 1 },
  memoBtn: { marginTop: 6, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8, borderWidth: 1, maxWidth: '100%' },
  memoBtnT: { fontSize: Math.round(12 * fs), fontWeight: '600' },
  memoInput: { borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, fontSize: Math.round(14 * fs), marginBottom: 4 },
  noiseCard: { borderRadius: 12, padding: 8, borderWidth: 1, marginBottom: 8 }, noiseRow: { flexDirection: 'row', gap: 4 },
  nb: { flex: 1, paddingHorizontal: 4, paddingVertical: 4, borderRadius: 6, borderWidth: 1, alignItems: 'center' }, nbT: { fontSize: Math.round(11 * fs), fontWeight: '600' },
  volTrack: { flexDirection: 'row', gap: 3, alignItems: 'center', paddingHorizontal: 6, paddingVertical: 5, borderRadius: 8 },
  volDot: { width: 14, height: 14, borderRadius: 7 },
  addTodoSheet: { borderTopLeftRadius: 20, borderTopRightRadius: 20, borderTopWidth: 1, padding: 20, paddingBottom: 32, maxHeight: '88%' },
  todoCard: { borderRadius: 12, padding: 10, borderWidth: 1 },
  todoH: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 5 },
  todoTitle: { fontSize: Math.round(14 * fs), fontWeight: '700' }, todoCnt: { fontSize: Math.round(11 * fs) },
  todoInput: { paddingHorizontal: 10, paddingVertical: 7, borderRadius: 8, borderWidth: 1, fontSize: Math.round(13 * fs), marginBottom: 4 },
  todoItem: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 5 },
  todoCk: { width: 20, height: 20, borderRadius: 4, borderWidth: 2, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  todoCkM: { color: 'white', fontSize: Math.round(12 * fs), fontWeight: '800' }, todoText: { flex: 1, fontSize: Math.round(13 * fs), lineHeight: 16 }, todoDel: { fontSize: Math.round(15 * fs), paddingHorizontal: 3 },
  todoActionBtn: { paddingHorizontal: 7, paddingVertical: 4, borderRadius: 6, borderWidth: 1, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  todoDelBtn: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  lapPanel: { position: 'absolute', bottom: 0, left: 8, right: 8, borderTopWidth: 2, borderLeftWidth: 2, borderRightWidth: 2, borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 20, elevation: 10, shadowColor: '#000', shadowOffset: { width: 0, height: -3 }, shadowOpacity: 0.15, shadowRadius: 8 },
  lapHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  lapTitle: { fontSize: Math.round(13 * fs), fontWeight: '700' },
  lapBigTime: { fontSize: Math.round(32 * fs), fontWeight: '900', fontVariant: ['tabular-nums'] },
  lapMiniCtrls: { flexDirection: 'row', gap: 6 },
  lapMiniBtn: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  lapMiniBtnT: { color: 'white', fontSize: Math.round(15 * fs), fontWeight: '800' },
  lapListToggle: { fontSize: Math.round(11 * fs), fontWeight: '700', textAlign: 'center', marginVertical: 4 },
  lapListScroll: { maxHeight: 120 },
  lapListRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 3, borderBottomWidth: 0.5 },
  lapListNum: { fontSize: Math.round(12 * fs), fontWeight: '600', width: 28 },
  lapListSplit: { fontSize: Math.round(14 * fs), fontWeight: '700', flex: 1, textAlign: 'center' },
  lapListTotal: { fontSize: Math.round(12 * fs), width: 50, textAlign: 'right' },
  lapBigRecordBtn: { marginTop: 8, paddingVertical: 16, borderRadius: 14, alignItems: 'center' },
  lapBigRecordT: { fontSize: Math.round(17 * fs), fontWeight: '900' },
  lapRecordBtn: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 12, alignItems: 'center', minWidth: 72 },
  lapRecordBtnT: { fontSize: Math.round(14 * fs), fontWeight: '900' },
  lapRecordBtnSub: { fontSize: Math.round(10 * fs), fontWeight: '600', marginTop: 2 },
  lapDoneBtn: { flex: 1, paddingVertical: 10, borderRadius: 10, alignItems: 'center' },
  lapDoneBtnT: { color: 'white', fontSize: Math.round(14 * fs), fontWeight: '800' },
  mo: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)' }, moScroll: { flexGrow: 1, justifyContent: 'center', paddingHorizontal: 20, paddingVertical: 30 },
  selfRatingSheet: { borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, paddingBottom: 36 },
  selfRatingHandle: { width: 40, height: 4, borderRadius: 2, alignSelf: 'center', marginBottom: 16 },
  selfRatingTitle: { fontSize: Math.round(18 * fs), fontWeight: '900', textAlign: 'center', marginBottom: 6 },
  selfRatingBtn: { flex: 1, borderRadius: 14, borderWidth: 1, paddingVertical: 14, alignItems: 'center' },
  modal: { borderRadius: 20, padding: 16, borderWidth: 1 }, modalTitle: { fontSize: Math.round(16 * fs), fontWeight: '900', textAlign: 'center', marginBottom: 10 },
  favSecLabel: { fontSize: Math.round(12 * fs), fontWeight: '700', marginBottom: 6 },
  favMgrGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 4 },
  favMgrChip: { flexDirection: 'row', alignItems: 'center', gap: 3, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 8, borderWidth: 1 },
  favMgrIcon: { fontSize: Math.round(13 * fs) }, favMgrChipT: { fontSize: Math.round(12 * fs), fontWeight: '700' }, favMgrX: { fontSize: Math.round(14 * fs), fontWeight: '600' },
  favAddChip: { flexDirection: 'row', alignItems: 'center', gap: 3, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 8, borderWidth: 1 },
  favAddIcon: { fontSize: Math.round(13 * fs) }, favAddChipT: { fontSize: Math.round(11 * fs), fontWeight: '600', maxWidth: 90 },
  favResetT: { fontSize: Math.round(12 * fs), fontWeight: '600' },
  favDoneBtn: { marginTop: 12, paddingVertical: 11, borderRadius: 10, alignItems: 'center' }, favDoneBtnT: { color: 'white', fontSize: Math.round(14 * fs), fontWeight: '800' },
  ms: { marginBottom: 14 }, ml: { fontSize: Math.round(12 * fs), fontWeight: '700', marginBottom: 6, textAlign: 'center' },
  typeRow: { flexDirection: 'row', borderRadius: 10, padding: 2, gap: 2, marginBottom: 14 },
  typeBtn: { flex: 1, paddingVertical: 8, borderRadius: 8, alignItems: 'center' }, typeBtnT: { fontSize: Math.round(12 * fs), fontWeight: '700' },
  presetRow: { flexDirection: 'row', gap: 4, flexWrap: 'wrap', justifyContent: 'center', marginTop: 8 },
  pc: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, borderWidth: 1 }, pcT: { fontSize: Math.round(11 * fs), fontWeight: '700' },
  mBtns: { flexDirection: 'row', gap: 8 },
  mCancel: { flex: 1, paddingVertical: 11, borderRadius: 10, borderWidth: 1, alignItems: 'center' }, mCancelT: { fontSize: Math.round(14 * fs), fontWeight: '600' },
  mConfirm: { flex: 1, paddingVertical: 11, borderRadius: 10, alignItems: 'center' }, mConfirmT: { color: 'white', fontSize: Math.round(14 * fs), fontWeight: '800' },
  // 울트라 포커스 + 모드
  ultraBanner: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 12, borderRadius: 12, borderWidth: 1, marginBottom: 8 },
  ultraBannerTitle: { fontSize: Math.round(14 * fs), fontWeight: '800' }, ultraBannerSub: { fontSize: Math.round(12 * fs), marginTop: 2 },
  ultraResumeBtn: { borderRadius: 14, padding: 14, alignItems: 'center', marginBottom: 8 },
  ultraResumeBtnT: { color: 'white', fontSize: Math.round(15 * fs), fontWeight: '900' },
  ultraStatus: { flexDirection: 'row', borderRadius: 8, padding: 8, borderWidth: 1, marginBottom: 6, alignItems: 'center', justifyContent: 'space-between' },
  modeBtn: { width: '100%', flexDirection: 'row', alignItems: 'center', gap: 12, padding: 16, borderRadius: 16, borderWidth: 1.5, marginTop: 12 },
  // 챌린지
  chalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.85)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  chalBox: { width: '100%', maxWidth: 360, borderRadius: 24, padding: 28, alignItems: 'center' },
  chalInfo: { width: '100%', borderRadius: 14, borderWidth: 1, padding: 14, alignItems: 'center', marginTop: 14 },
  chalTargetBox: { width: '100%', borderRadius: 10, borderWidth: 1.5, padding: 12, alignItems: 'center', marginTop: 8 },
  chalInput: { width: '100%', borderRadius: 10, borderWidth: 2, padding: 12, fontSize: Math.round(15 * fs), fontWeight: '700', textAlign: 'center', marginTop: 8, letterSpacing: 0 },
  chalBtn: { width: '100%', borderRadius: 14, padding: 16, alignItems: 'center', marginTop: 14 },
  // 가이드 말풍선
  guideBubble: { borderRadius: 10, padding: 12, borderWidth: 1, marginTop: 10, width: '100%' },
  // 잠금 오버레이 (하드코딩 색상 — T 미사용)
  // iOS: presentationStyle="fullScreen" + transparent={false} 환경에서 flex:1이 모달 창을 채우지 못하는 버그 방지
  // → position absolute로 명시적 전체 커버
  lockOverlayBg: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.95)', justifyContent: 'center', alignItems: 'center', paddingHorizontal: 30 },
  lockMsg: { fontSize: Math.round(16 * fs), fontWeight: '800', color: 'white', marginTop: 14, textAlign: 'center' },
  lockTimer: { fontSize: Math.round(52 * fs), fontWeight: '900', color: 'white', letterSpacing: 4, marginBottom: 6 },
  lockModeBadge: { fontSize: Math.round(14 * fs), fontWeight: '700', color: '#FF6B6B', marginBottom: 20 },
  lockPauseBtn: { paddingHorizontal: 20, paddingVertical: 10, borderRadius: 20, borderWidth: 1, borderColor: '#FFB74D60', marginBottom: 20 },
  lockPauseBtnT: { fontSize: Math.round(14 * fs), fontWeight: '700', color: '#FFB74D' },
  lockSlideWrap: { alignItems: 'center', position: 'absolute', left: 0, right: 0 },
  lockSlideHint: { fontSize: Math.round(14 * fs), fontWeight: '700', color: 'rgba(255,255,255,0.5)', marginBottom: 14, letterSpacing: 1 },
  lockSlideTrack: { height: 56, borderRadius: 28, backgroundColor: 'rgba(255,255,255,0.1)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)', justifyContent: 'center' },
  lockSlideThumb: { width: 56, height: 54, borderRadius: 27, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' },
}); }
