// stats/styles.js — StatsScreen 스타일
import { StyleSheet, Platform } from 'react-native';

export const HM_WEEKS = 16;
export const HM_GAP   = 2;

export function createStyles(fs) { return StyleSheet.create({
  container: { flex: 1 },
  scroll: { paddingHorizontal: 16, paddingTop: 8 },

  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  headerTitle: { fontSize: Math.round(20 * fs), fontWeight: '900' },
  tabRow: { flexDirection: 'row', borderRadius: 8, padding: 2, gap: 2 },
  tabBtn: { paddingHorizontal: 9, paddingVertical: 5, borderRadius: 6 },
  tabText: { fontSize: Math.round(12 * fs), fontWeight: '700' },

  summaryRow: { flexDirection: 'row', gap: 6, marginBottom: 8 },
  summaryCard: { flex: 1, borderRadius: 12, padding: 10, borderWidth: 1, alignItems: 'center' },
  sLabel: { fontSize: Math.round(11 * fs), fontWeight: '600' },
  sVal: { fontSize: Math.round(15 * fs), fontWeight: '900', marginTop: 2, textAlign: 'center' },
  sSub: { fontSize: Math.round(10 * fs), fontWeight: '600', marginTop: 2 },

  card: { borderRadius: 14, padding: 12, borderWidth: 1, marginBottom: 8 },
  secLabel: { fontSize: Math.round(12 * fs), fontWeight: '700', marginBottom: 8 },

  weakCard: { borderRadius: 12, padding: 12, borderWidth: 1, marginBottom: 8 },
  weakTitle: { fontSize: Math.round(13 * fs), fontWeight: '800', marginBottom: 6 },
  weakChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  weakChip: { paddingHorizontal: 9, paddingVertical: 4, borderRadius: 8, borderWidth: 1 },
  weakChipT: { fontSize: Math.round(13 * fs), fontWeight: '700' },

  reportBtn: { flexDirection: 'row', alignItems: 'center', borderRadius: 14, padding: 14, gap: 10, marginBottom: 8 },
  reportBtnIcon: { fontSize: Math.round(24 * fs) },
  reportBtnTitle: { color: 'white', fontSize: Math.round(14 * fs), fontWeight: '800' },
  reportBtnSub: { color: 'rgba(255,255,255,0.75)', fontSize: Math.round(12 * fs), marginTop: 1 },
  reportBtnArrow: { color: 'white', fontSize: Math.round(16 * fs), marginLeft: 'auto' },

  reportCard: { borderRadius: 20, overflow: 'hidden', borderWidth: 1, ...Platform.select({ ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.12, shadowRadius: 12 }, android: { elevation: 6 } }) },
  reportCardHeader: { padding: 16, alignItems: 'center', gap: 4 },
  reportCardHeaderT: { color: 'white', fontSize: Math.round(16 * fs), fontWeight: '900' },
  reportCardHeaderSub: { color: 'rgba(255,255,255,0.8)', fontSize: Math.round(13 * fs) },
  reportMetrics: { flexDirection: 'row', padding: 16, alignItems: 'center' },
  reportMetricItem: { flex: 1, alignItems: 'center', gap: 4 },
  reportMetricVal: { fontSize: Math.round(18 * fs), fontWeight: '900' },
  reportMetricLabel: { fontSize: Math.round(11 * fs), fontWeight: '600' },
  reportMetricDivider: { width: 1, height: 36 },
  reportMiniCard: { borderRadius: 12, padding: 12 },
  reportCompareLabel: { fontSize: Math.round(13 * fs), fontWeight: '600' },
  reportCompareVal: { fontSize: Math.round(15 * fs), fontWeight: '900' },
  reportTopSubj: { marginHorizontal: 16, marginBottom: 12 },
  reportTopSubjLabel: { fontSize: Math.round(12 * fs), fontWeight: '700' },
  reportTopSubjName: { fontSize: Math.round(14 * fs), fontWeight: '800' },
  reportStreak: { marginHorizontal: 16, borderRadius: 10, padding: 10, flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 16, borderWidth: 1 },
  reportStreakT: { fontSize: Math.round(14 * fs), fontWeight: '800' },
  reportTransparency: { marginHorizontal: 16, borderRadius: 12, padding: 14, marginBottom: 16 },
  reportTransTitle: { fontSize: Math.round(14 * fs), fontWeight: '800', marginBottom: 10, textAlign: 'center' },
  reportTransRow: { flexDirection: 'row', justifyContent: 'space-around' },
  reportTransItem: { alignItems: 'center' },
  shareBtn: { marginHorizontal: 16, borderRadius: 12, paddingVertical: 12, alignItems: 'center', marginBottom: 8 },
  shareBtnT: { color: 'white', fontSize: Math.round(15 * fs), fontWeight: '800' },

  tierRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 4 },
  tierBig: { width: 46, height: 46, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  tierBigT: { fontSize: Math.round(20 * fs), fontWeight: '900' },
  tierScore: { fontSize: Math.round(15 * fs), fontWeight: '800' },
  tierMsg: { fontSize: Math.round(12 * fs), fontWeight: '600', marginTop: 1 },

  barRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 5, gap: 6 },
  barDay: { width: 14, fontSize: Math.round(12 * fs), fontWeight: '700', textAlign: 'center' },
  barTrack: { flex: 1, height: 8, borderRadius: 4, overflow: 'hidden' },
  barFill: { height: '100%', borderRadius: 4 },
  barTime: { width: 35, fontSize: Math.round(12 * fs), fontWeight: '600', textAlign: 'right' },

  densityChart: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'flex-end', height: 80 },
  densityCol: { alignItems: 'center', gap: 3 },
  densityBar: { width: 16, borderRadius: 3 },
  densityDay: { fontSize: Math.round(11 * fs), fontWeight: '700' },
  densityTier: { fontSize: Math.round(11 * fs), fontWeight: '800' },

  tlRow: { flexDirection: 'row', alignItems: 'flex-end', height: 50, gap: 1 },
  tlCol: { flex: 1, alignItems: 'center' },
  tlBar: { width: '100%', borderRadius: 1, minWidth: 2 },
  tlLabel: { fontSize: Math.round(11 * fs), marginTop: 2 },

  tzRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8, gap: 6 },
  tzIcon: { fontSize: Math.round(15 * fs), width: 20 },
  tzLabel: { fontSize: Math.round(12 * fs), fontWeight: '700', width: 28 },
  tzBarWrap: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 6 },
  tzBarTrack: { flex: 1, height: 7, borderRadius: 3.5, overflow: 'hidden' },
  tzBarFill: { height: '100%', borderRadius: 3.5 },
  tzTime: { fontSize: Math.round(11 * fs), minWidth: 34, textAlign: 'right' },
  tzTierBadge: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6 },
  tzTierT: { fontSize: Math.round(11 * fs), fontWeight: '800' },
  tzEmpty: { fontSize: Math.round(11 * fs), width: 30, textAlign: 'center' },
  bestZoneBanner: { flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 8, padding: 8, borderWidth: 1, marginTop: 4 },
  bestZoneT: { fontSize: Math.round(13 * fs), fontWeight: '700' },

  stackBar: { height: 8, borderRadius: 4, flexDirection: 'row', overflow: 'hidden', marginBottom: 8 },
  stackSeg: { height: '100%' },
  subjRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 3 },
  subjDot: { width: 8, height: 8, borderRadius: 4 },
  subjName: { flex: 1, fontSize: Math.round(13 * fs), fontWeight: '600' },
  subjPct: { fontSize: Math.round(12 * fs) },
  subjTime: { fontSize: Math.round(12 * fs), fontWeight: '700', width: 35, textAlign: 'right' },

  monthNav: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  monthArrow: { fontSize: Math.round(15 * fs), fontWeight: '800', paddingHorizontal: 8 },
  monthTitle: { fontSize: Math.round(15 * fs), fontWeight: '900' },
  calWeekRow: { flexDirection: 'row', marginBottom: 4 },
  calWeekDay: { flex: 1, textAlign: 'center', fontSize: Math.round(11 * fs), fontWeight: '700' },
  calGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  calCell: { width: `${100 / 7}%`, alignItems: 'center', paddingVertical: 2, padding: 3 },
  calDot: { borderRadius: 6, alignItems: 'center', justifyContent: 'center', width: '100%', aspectRatio: 1 },
  calDay: { fontSize: Math.round(12 * fs), fontWeight: '700' },
  calTime: { fontSize: Math.round(11 * fs), marginTop: 1 },

  heatLegend: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 3, marginTop: 8 },
  heatBox: { width: 12, height: 12, borderRadius: 2 },
  heatLegendT: { fontSize: Math.round(11 * fs), fontWeight: '600' },

  hmHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
  hmBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8 },
  hmBadgeT: { fontSize: Math.round(13 * fs), fontWeight: '800' },
  hmMonthRow: { flexDirection: 'row', marginBottom: 2 },
  hmMonthLabel: { fontSize: Math.round(11 * fs), fontWeight: '600' },
  hmGrid: { flexDirection: 'row' },
  hmDayLabels: { flexDirection: 'column', gap: HM_GAP, marginRight: HM_GAP, paddingTop: 0 },
  hmDayLabel: { fontSize: Math.round(11 * fs), fontWeight: '600', width: 14, textAlign: 'right' },
  hmCell: { borderRadius: 2 },

  insightCard: { borderRadius: 14, padding: 12, borderWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 },
  insightText: { flex: 1, fontSize: Math.round(14 * fs), fontWeight: '600', lineHeight: 17 },

  emptyText: { fontSize: Math.round(13 * fs), textAlign: 'center', paddingVertical: 8 },

  diaryGroup: { marginBottom: 10 },
  diaryDate: { fontSize: Math.round(12 * fs), fontWeight: '800', marginBottom: 4 },
  diaryRow: { borderLeftWidth: 3, paddingLeft: 8, marginBottom: 5, paddingVertical: 2 },
  diaryMemo: { fontSize: Math.round(14 * fs), fontWeight: '600', lineHeight: 17 },
  diaryMeta: { fontSize: Math.round(11 * fs), marginTop: 1 },
  memoEditInput: { borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, fontSize: Math.round(14 * fs), marginBottom: 4 },
  modalTitle: { fontSize: Math.round(16 * fs), fontWeight: '900', textAlign: 'center', marginBottom: 12 },

  mo: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)' },
  moScroll: { flexGrow: 1, paddingHorizontal: 20, paddingVertical: 20 },
  mCancel: { marginHorizontal: 16, marginBottom: 16, paddingVertical: 10, borderRadius: 10, borderWidth: 1, alignItems: 'center' },
  mCancelT: { fontSize: Math.round(14 * fs), fontWeight: '600' },
  mConfirm: { marginHorizontal: 16, marginBottom: 16, paddingVertical: 10, borderRadius: 10, alignItems: 'center' },
  mConfirmT: { color: 'white', fontSize: Math.round(14 * fs), fontWeight: '700' },

  weekNavRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderRadius: 12, borderWidth: 1, padding: 8, marginBottom: 8 },
  weekNavBtn: { padding: 8 },
  weekNavArrow: { fontSize: Math.round(18 * fs), fontWeight: '700' },
  weekNavTitle: { fontSize: Math.round(15 * fs), fontWeight: '800' },

  sessCard: { borderLeftWidth: 4, borderLeftColor: '#ccc', paddingLeft: 10, paddingVertical: 8, marginBottom: 8, borderRadius: 4 },
  tierSmallBadge: { borderRadius: 6, paddingHorizontal: 7, paddingVertical: 2 },

  hmStatRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around' },
  hmStatItem: { alignItems: 'center', flex: 1, paddingVertical: 4 },
  hmStatVal: { fontSize: Math.round(15 * fs), fontWeight: '800', marginBottom: 2 },
  hmStatLabel: { fontSize: Math.round(12 * fs) },
  hmStatDivider: { width: 1, height: 32, opacity: 0.3 },

  dayDetailSheet: { width: '100%', borderTopLeftRadius: 20, borderTopRightRadius: 20, maxHeight: '88%', padding: 20, paddingBottom: 36 },
  moBottom: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },

  subjPeriodRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  subjPeriodBtn: { flex: 1, paddingVertical: 8, borderRadius: 8, alignItems: 'center', borderWidth: 1 },
  subjPeriodBtnT: { fontSize: Math.round(14 * fs), fontWeight: '700' },
  subjListItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, gap: 8 },
  subjListBarTrack: { flex: 1, height: 6, borderRadius: 3, overflow: 'hidden', backgroundColor: 'rgba(0,0,0,0.08)' },
  subjListBarFill: { height: 6, borderRadius: 3 },
  subjInsightCard: { borderRadius: 12, padding: 14, marginTop: 12, gap: 10 },
  subjInsightRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },

}); }
